In [2]:
import cirq
import numpy as np

In [10]:
from typing import *
def get_Hamiltonian(N: int, 
                    indices: List[Tuple[int,int]], 
                    angles: Union[List[float], np.ndarray[float]]) -> np.ndarray:
    if len(indices) != len(angles):
        raise ValueError('The length of indices and angles must match..')
    q = [cirq.NamedQubit(name=f'q_{i}') for i in range(N)]
    H = sum([angles[i]*(cirq.X(q[indices[i][0]])*cirq.X(q[indices[i][1]])+cirq.Y(q[indices[i][0]])*cirq.Y(q[indices[i][1]])) for i in range(len(angles))])
    return H.matrix()

N = 12
indices = [(i,i+1) for i in range(N-1)]
angles = np.random.uniform(-2*np.pi,2*np.pi, len(indices))
H = get_Hamiltonian(N=N,
                indices=indices,
                angles=angles)

In [6]:
from qulacs import QuantumCircuit, ParametricQuantumCircuit
from qulacs.gate import X, Z, H, CNOT
import numpy as np

# Step 1: Create a quantum circuit with a specified number of qubits
num_qubits = 2
circuit = QuantumCircuit(num_qubits)

# Step 2: Add gates to the circuit
# For example, adding an H gate on the first qubit and a CNOT gate
circuit.add_gate(H(0))  # Hadamard gate on qubit 0
circuit.add_gate(CNOT(0, 1))  # CNOT gate with control qubit 0 and target qubit 1

# Step 3: Get the total matrix representation of the circuit
matrix = circuit.to_density_matrix()
print("Matrix representation of the quantum circuit:")
print(matrix)


AttributeError: 'qulacs_core.QuantumCircuit' object has no attribute 'to_density_matrix'

In [9]:
import numpy as np

x = 1.223
U = np.array([[np.cos(x/2), 0, 0, -1j*np.sin(x/2)],
              [0, np.cos(x/2), -1j*np.sin(x/2), 0],
              [0, -1j*np.sin(x/2), np.cos(x/2), 0],
              [-1j*np.sin(x/2), 0, 0, np.cos(x/2)]])
state = np.array([1,0,0,0])
U@state

array([0.81878779+0.j        , 0.        +0.j        ,
       0.        +0.j        , 0.        -0.57409629j])

In [18]:
a = np.array([9.53333781e-01+9.81307787e-18j, 5.55111512e-17-3.92523115e-17j,
       4.90653893e-17-5.55111512e-17j, 3.92523115e-17-3.01918371e-01j])
a

array([9.53333781e-01+9.81307787e-18j, 5.55111512e-17-3.92523115e-17j,
       4.90653893e-17-5.55111512e-17j, 3.92523115e-17-3.01918371e-01j])

In [19]:
a[np.abs(a) <= 9e-15] = 0
a

array([9.53333781e-01+9.81307787e-18j, 0.00000000e+00+0.00000000e+00j,
       0.00000000e+00+0.00000000e+00j, 3.92523115e-17-3.01918371e-01j])